#ifndef _OPCODES_H
#define _OPCODES_H

enum Opcodes {
	MSG_NULL_ACTION									= 0,
	CMSG_BOOTME									,	
	CMSG_DBLOOKUP								,	
	SMSG_DBLOOKUP								,	
	CMSG_DEBUG_CHANGECELLZONE						,	
	CMSG_EMBLAZON_TABARD_OBSOLETE					,	
	CMSG_UNEMBLAZON_TABARD_OBSOLETE					,	
	CMSG_RECHARGE									,	
	CMSG_MAKEMONSTERATTACKME_OBSOLETE				,	
	CMSG_MAKEMONSTERATTACKGUID						,	
	CMSG_ENABLEDEBUGCOMBATLOGGING_OBSOLETE			,	
	SMSG_ATTACKERSTATEUPDATEDEBUGINFO_OBSOLETE		,	
	SMSG_DEBUGINFOSPELL_OBSOLETE					,	
	SMSG_DEBUGINFOSPELLMISS_OBSOLETE				,	
	SMSG_DEBUG_PLAYER_RANGE_OBSOLETE				,	
	CMSG_UNDRESSPLAYER								,	
	CMSG_BEASTMASTER								,	
	CMSG_CHEAT_SETMONEY								,	
	CMSG_LEVEL_CHEAT								,	
	CMSG_LEVELUP_CHEAT_OBSOLETE						,	
	CMSG_COOLDOWN_CHEAT								,	
	CMSG_USE_SKILL_CHEAT							,	
	CMSG_SEND_EVENT									,	
	CMSG_DEBUG_AISTATE								,	
	SMSG_DEBUG_AISTATE								,	
	CMSG_ADVANCE_SPAWN_TIME							,	
// 	CMSG_AUTH_SRP6_BEGIN							,	
// 	CMSG_AUTH_SRP6_PROOF							,	
// 	CMSG_AUTH_SRP6_RECODE							,	
// 	CMSG_CHAR_CREATE								,	
// 	CMSG_CHAR_ENUM									,	
// 	CMSG_CHAR_DELETE								,	
	SMSG_AUTH_SRP6_RESPONSE							,	
// 	SMSG_CHAR_CREATE								,	
// 	SMSG_CHAR_ENUM									,	
// 	SMSG_CHAR_DELETE								,	
// 	CMSG_PLAYER_LOGIN								,	
// 	SMSG_CHARACTER_LOGIN_FAILED						,	
	SMSG_LOGOUT_COMPLETE							,	
	SMSG_LOGOUT_CANCEL_ACK							,	

	CMSG_GAMEOBJ_CHAIR_USE_OBSOLETE					,	

	CMSG_TRIGGER_CINEMATIC_CHEAT					,	
	CMSG_OPENING_CINEMATIC							,	
	SMSG_TRIGGER_CINEMATIC							,	
	CMSG_NEXT_CINEMATIC_CAMERA						,	
	CMSG_STORE_LOOT_IN_SLOT							,	

	CMSG_UNUSED										,	
	CMSG_UNUSED2									,	
	CMSG_SHEATHE_OBSOLETE							,	
	CMSG_SAVE_PLAYER								,	
	CMSG_SETDEATHBINDPOINT							,	
	CMSG_GETDEATHBINDZONE							,	
	SMSG_BINDZONEREPLY								,	
	SMSG_MOUNTRESULT								,	
	SMSG_DISMOUNTRESULT								,	
	SMSG_PUREMOUNT_CANCELLED_OBSOLETE				,	
	SMSG_MOUNTSPECIAL_ANIM							,	
	SMSG_TRAINER_BUY_SUCCEEDED						,	
	SMSG_TRAINER_BUY_FAILED							,	
	SMSG_PLAYERBINDERROR							,	
	CMSG_PLAYER_MACRO_OBSOLETE						,	
	SMSG_PLAYER_MACRO_OBSOLETE						,	
	CMSG_GHOST										,	
	SMSG_INVALID_PROMOTION_CODE						,	
	SMSG_AUTH_CHALLENGE								,	
	CMSG_AUTH_SESSION								,	
	SMSG_AUTH_RESPONSE								,	
	SMSG_COMPRESSED_UPDATE_OBJECT					,	
	SMSG_OBSOLETE									,	
	MSG_LOOKING_FOR_GROUP							,	
	CMSG_SET_LOOKING_FOR_GROUP						,	
	CMSG_DECHARGE									,	
	SMSG_ACCOUNT_DATA_MD5							,	
	CMSG_REQUEST_ACCOUNT_DATA						,	
	CMSG_UPDATE_ACCOUNT_DATA						,	
	SMSG_UPDATE_ACCOUNT_DATA						,	
	SMSG_CLEAR_FAR_SIGHT_IMMEDIATE					,	
	SMSG_POWERGAINLOG_OBSOLETE						,	
	SMSG_GAMEOBJECT_SPAWN_ANIM						,	
	SMSG_CHAT_WRONG_FACTION							,	
	CMSG_SET_STAT_CHEAT								,	
	CMSG_CHARACTER_POINT_CHEAT						,	
	CMSG_CHAT_IGNORED								,	
	CMSG_CLEAR_EXPLORATION							,	
	CMSG_TAXICLEARNODE								,	
	CMSG_TAXIENABLENODE								,	
	SMSG_DEBUGAURAPROC								,	
	SMSG_PROCRESIST									,	
	SMSG_STANDSTATE_CHANGE_FAILURE					,	
	SMSG_DISPEL_FAILED								,	
	CMSG_SET_AMMO									,	
	CMSG_PLAYER_AI_CHEAT							,	
	MSG_GM_ACCOUNT_ONLINE							,	
	SMSG_DAMAGE_CALC_LOG							,	
	CMSG_ENABLE_DAMAGE_LOG							,	
	CMSG_REQUEST_PARTY_MEMBER_STATS					,	
	CMSG_GROUP_SWAP_SUB_GROUP						,	
	CMSG_RESET_FACTION_CHEAT						,	
	CMSG_SET_DURABILITY_CHEAT						,	
	SMSG_AUCTION_REMOVED_NOTIFICATION				,	
	CMSG_MEETINGSTONE_JOIN							,	
	CMSG_MEETINGSTONE_LEAVE							,	
	CMSG_MEETINGSTONE_CHEAT							,	
	SMSG_MEETINGSTONE_SETQUEUE						,	
	CMSG_MEETINGSTONE_INFO							,	
	SMSG_MEETINGSTONE_COMPLETE						,	
	SMSG_MEETINGSTONE_IN_PROGRESS					,	
	SMSG_MEETINGSTONE_MEMBER_ADDED					,	
	SMSG_STANDSTATE_CHANGE_ACK						,	
	SMSG_GAMEOBJECT_RESET_STATE						,	
	MSG_MOVE_TOGGLE_GRAVITY_CHEAT					,	
	SMSG_MONSTER_MOVE_TRANSPORT						,	
	SMSG_FEIGN_DEATH_RESISTED						,	
	SMSG_SCRIPT_MESSAGE								,	
	SMSG_MEETINGSTONE_JOINFAILED					,	
	SMSG_DURABILITY_DAMAGE_DEATH					,	
	CMSG_SET_EXPLORATION							,	
// 	CMSG_CHAR_RENAME								,	
// 	SMSG_CHAR_RENAME								,	
	SMSG_INSTANCE_SAVE_CREATED						,	
	CMSG_GM_UNTEACH									,	
	SMSG_WARDEN_DATA								,	
	CMSG_WARDEN_DATA								,	
	SMSG_ADDON_INFO									,	
	SMSG_PLAY_TIME_WARNING							,	
	SMSG_MINIGAME_SETUP								,	
	SMSG_MINIGAME_STATE								,	
	CMSG_MINIGAME_MOVE								,	
	SMSG_MINIGAME_MOVE_FAILED						,	
	// 787 related to reputation
	CMSG_SET_FACTION_INACTIVE						,	
	CMSG_UNKNOWN_1									,	
	SMSG_UNKNOWN_DEMON								,	
	// 808 // (0x0328)
	SMSG_SET_ANTISPAM_REGEX							,	
	// 815 //(0x032F) // something related to INSTAKILL
	// 816 //(0x0320) // something related to spells
	SMSG_PVP_CAPTURE_STATE_MSG						,	
	SMSG_PVP_NOTIFY									,	
	CMSG_SOCKET_GEMS								,	
	// 855 //(0x0357) // also something with arena SMSG_unk
	CMSG_ENABLE_AUTOJOIN							,	
	CMSG_DISABLE_AUTOJOIN							,	
	CMSG_ENABLE_AUTOADD_MEMBERS						,	
	CMSG_DISABLE_AUTOADD_MEMBERS					,	
	CMSG_LFG_INVITE_ACCEPT							,	
	CMSG_LFG_INVITE_CANCEL							,	
	CMSG_CLEAR_LOOKING_FOR_GROUP_STATE				,	
	CMSG_SET_LOOKING_FOR_NONE						,	
	CMSG_SET_LOOKING_FOR_MORE						,	
	CMSG_SET_LOOKING_FOR_GROUP_COMMENT				,	
	SMSG_LFG_MATCHMAKING_TIMEDOUT                   ,	
	SMSG_LFG_MATCHMAKING_OTHER_TIMEDOUT             ,	
	SMSG_LFG_MATCHMAKING_AUTOJOIN_FAILED            ,	
	SMSG_LFG_MATCHMAKING_AUTOJOIN_FAILED_NO_PLAYER  ,	
	SMSG_LFG_INVITE									,	
	SMSG_SET_VISIBLE_RANK							,	
	SMSG_FLIGHT_SPLINE_SYNC							,	
	SMSG_REALM_SPLIT_STATE_RESPONSE					,	
	CMSG_REALM_SPLIT_STATE_REQUEST					,	
	// 911
	SMSG_TICKCOUNT_QUERY							,	
	CMSG_TICKCOUNT_QUERY_RESPONSE					,	
	// 938
	//949
	//951 
	SMSG_ACTIVATE_SPAM_REPORTING					,
	// 964 //(0x03C4)
	SMSG_DISCONNECT_CLIENT							,
	CMSG_COMPLAIN_CHAT								,
	SMSG_CHANNEL_NOTIFY_AVAILABLE_VOICE_SESSION		,
	CMSG_ADD_MUTE									, // this one is also a smsg
	CMSG_DELETE_MUTE								,
	CMSG_SILENCE_MEMBER								,
	CMSG_UNSILENCE_MEMBER							,
	CMSG_CHANNEL_VOICE_QUERY						, // enable disable PVP_REPORT_AFK_SYSTEM
	SMSG_UNIT_UNKNOWN								,
	C_ENTER_GAME,
	NUM_MSG_TYPES									,
};



/*
0	= Universal
1	= ?Orcish?
2	= Darnassian
3	= Taurahe
4	= ?
5	= ?
6	= Dwarvish
7	= Common
8	= Demonic
9	= Titan
10	= Thelassian
11	= Draconic
12	= Kalimag
13	= Gnomish
14	= Troll
*/

/*
2.3.0 stuff
1			= guide
2			= questgiver
16			= trainer (class)
128			= vendor
4096		= repairer
8192		= taxi
16384		= trainer (profession)
32768		= spirit healer
65536		= binder
131072		= banker
262144		= charter vendor
524288		= tabard vendor
1048576		= battle master
2097152		= auction house
4194304		= stabler
8388608		= guild bank
*/

//enum FieldFlags {
//	0x00000008	== can't climb slopes too steep
//	0x40000000	== sheathed
//};

#endif
