//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace clientmsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CharInfo")]
  public partial class CharInfo : global::ProtoBuf.IExtensible
  {
    public CharInfo() {}
    

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private ulong _user_account = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private uint _head = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint head
    {
      get { return _head; }
      set { _head = value; }
    }

    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MapCharInfo")]
  public partial class MapCharInfo : global::ProtoBuf.IExtensible
  {
    public MapCharInfo() {}
    

    private clientmsg.CharInfo _charinfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public clientmsg.CharInfo charinfo
    {
      get { return _charinfo; }
      set { _charinfo = value; }
    }

    private uint _x = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint x
    {
      get { return _x; }
      set { _x = value; }
    }

    private uint _y = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint y
    {
      get { return _y; }
      set { _y = value; }
    }

    private uint _dir = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    

    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _pwd = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pwd
    {
      get { return _pwd; }
      set { _pwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResponse")]
  public partial class LoginResponse : global::ProtoBuf.IExtensible
  {
    public LoginResponse() {}
    

    private string _gate_ip = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gate_ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gate_ip
    {
      get { return _gate_ip; }
      set { _gate_ip = value; }
    }

    private uint _gate_port = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gate_port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gate_port
    {
      get { return _gate_port; }
      set { _gate_port = value; }
    }

    private ulong _user_account = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }

    private clientmsg.enumLoginResult _result = clientmsg.enumLoginResult.enumLoginResult_Success;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(clientmsg.enumLoginResult.enumLoginResult_Success)]
    public clientmsg.enumLoginResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginGame")]
  public partial class LoginGame : global::ProtoBuf.IExtensible
  {
    public LoginGame() {}
    
    private ulong _user_account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientInit")]
  public partial class ClientInit : global::ProtoBuf.IExtensible
  {
    public ClientInit() {}
    

    private clientmsg.CharInfo _charinfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public clientmsg.CharInfo charinfo
    {
      get { return _charinfo; }
      set { _charinfo = value; }
    }

    private clientmsg.enumGetCharResult _result = clientmsg.enumGetCharResult.Response_Success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(clientmsg.enumGetCharResult.Response_Success)]
    public clientmsg.enumGetCharResult result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateChar")]
  public partial class CreateChar : global::ProtoBuf.IExtensible
  {
    public CreateChar() {}
    

    private clientmsg.CharInfo _charinfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public clientmsg.CharInfo charinfo
    {
      get { return _charinfo; }
      set { _charinfo = value; }
    }

    private uint _mapid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint mapid
    {
      get { return _mapid; }
      set { _mapid = value; }
    }

    private uint _cityid = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cityid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cityid
    {
      get { return _cityid; }
      set { _cityid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientExit")]
  public partial class ClientExit : global::ProtoBuf.IExtensible
  {
    public ClientExit() {}
    

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private ulong _user_account = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_account", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong user_account
    {
      get { return _user_account; }
      set { _user_account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SendChat")]
  public partial class SendChat : global::ProtoBuf.IExtensible
  {
    public SendChat() {}
    

    private clientmsg.enumChatType _type = clientmsg.enumChatType.Chat_User;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(clientmsg.enumChatType.Chat_User)]
    public clientmsg.enumChatType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private uint _charid = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint charid
    {
      get { return _charid; }
      set { _charid = value; }
    }

    private string _msg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"enumGetCharResult")]
    public enum enumGetCharResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Response_Success", Value=0)]
      Response_Success = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Response_SystemError", Value=1)]
      Response_SystemError = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Response_NewChar", Value=2)]
      Response_NewChar = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CommonConst")]
    public enum CommonConst
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_NAMESIZE", Value=32)]
      MAX_NAMESIZE = 32
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SCREEN_CONST")]
    public enum SCREEN_CONST
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCREEN_WIDTH", Value=13)]
      SCREEN_WIDTH = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCREEN_HEIGHT", Value=19)]
      SCREEN_HEIGHT = 19
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DIR")]
    public enum DIR
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_UP", Value=0)]
      DIR_UP = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_UPRIGHT", Value=1)]
      DIR_UPRIGHT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_RIGHT", Value=2)]
      DIR_RIGHT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_DOWNRIGHT", Value=3)]
      DIR_DOWNRIGHT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_DOWN", Value=4)]
      DIR_DOWN = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_DOWNLEFT", Value=5)]
      DIR_DOWNLEFT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_LEFT", Value=6)]
      DIR_LEFT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_UPLEFT", Value=7)]
      DIR_UPLEFT = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DIR_ERROR", Value=8)]
      DIR_ERROR = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"enumLoginResult")]
    public enum enumLoginResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumLoginResult_Success", Value=0)]
      enumLoginResult_Success = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumLoginResult_Fail", Value=1)]
      enumLoginResult_Fail = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumLoginResult_NameFail", Value=2)]
      enumLoginResult_NameFail = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumLoginResult_PwdFail", Value=3)]
      enumLoginResult_PwdFail = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"enumLoginResult_HaveLogin", Value=4)]
      enumLoginResult_HaveLogin = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"enumChatType")]
    public enum enumChatType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Chat_User", Value=1)]
      Chat_User = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Chat_World", Value=2)]
      Chat_World = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Chat_Sys", Value=3)]
      Chat_Sys = 3
    }
  
}