// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageFarmC2S.proto

#ifndef PROTOBUF_MessageFarmC2S_2eproto__INCLUDED
#define PROTOBUF_MessageFarmC2S_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "MsgHead.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageFarmC2S_2eproto();
void protobuf_AssignDesc_MessageFarmC2S_2eproto();
void protobuf_ShutdownFile_MessageFarmC2S_2eproto();

class MsgFarmStateReq;
class MsgSeedCellReq;
class MsgSpreadManureReq;
class MsgGatherPloughCellReq;
class MsgWaterCellReq;

// ===================================================================

class MsgFarmStateReq : public ::google::protobuf::Message {
 public:
  MsgFarmStateReq();
  virtual ~MsgFarmStateReq();
  
  MsgFarmStateReq(const MsgFarmStateReq& from);
  
  inline MsgFarmStateReq& operator=(const MsgFarmStateReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgFarmStateReq& default_instance();
  
  void Swap(MsgFarmStateReq* other);
  
  // implements Message ----------------------------------------------
  
  MsgFarmStateReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgFarmStateReq& from);
  void MergeFrom(const MsgFarmStateReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:MsgFarmStateReq)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_MessageFarmC2S_2eproto();
  friend void protobuf_AssignDesc_MessageFarmC2S_2eproto();
  friend void protobuf_ShutdownFile_MessageFarmC2S_2eproto();
  
  void InitAsDefaultInstance();
  static MsgFarmStateReq* default_instance_;
};
// -------------------------------------------------------------------

class MsgSeedCellReq : public ::google::protobuf::Message {
 public:
  MsgSeedCellReq();
  virtual ~MsgSeedCellReq();
  
  MsgSeedCellReq(const MsgSeedCellReq& from);
  
  inline MsgSeedCellReq& operator=(const MsgSeedCellReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgSeedCellReq& default_instance();
  
  void Swap(MsgSeedCellReq* other);
  
  // implements Message ----------------------------------------------
  
  MsgSeedCellReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgSeedCellReq& from);
  void MergeFrom(const MsgSeedCellReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 seedlevel = 1;
  inline bool has_seedlevel() const;
  inline void clear_seedlevel();
  static const int kSeedlevelFieldNumber = 1;
  inline ::google::protobuf::int32 seedlevel() const;
  inline void set_seedlevel(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:MsgSeedCellReq)
 private:
  inline void set_has_seedlevel();
  inline void clear_has_seedlevel();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 seedlevel_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageFarmC2S_2eproto();
  friend void protobuf_AssignDesc_MessageFarmC2S_2eproto();
  friend void protobuf_ShutdownFile_MessageFarmC2S_2eproto();
  
  void InitAsDefaultInstance();
  static MsgSeedCellReq* default_instance_;
};
// -------------------------------------------------------------------

class MsgSpreadManureReq : public ::google::protobuf::Message {
 public:
  MsgSpreadManureReq();
  virtual ~MsgSpreadManureReq();
  
  MsgSpreadManureReq(const MsgSpreadManureReq& from);
  
  inline MsgSpreadManureReq& operator=(const MsgSpreadManureReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgSpreadManureReq& default_instance();
  
  void Swap(MsgSpreadManureReq* other);
  
  // implements Message ----------------------------------------------
  
  MsgSpreadManureReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgSpreadManureReq& from);
  void MergeFrom(const MsgSpreadManureReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 manurelevel = 1;
  inline bool has_manurelevel() const;
  inline void clear_manurelevel();
  static const int kManurelevelFieldNumber = 1;
  inline ::google::protobuf::int32 manurelevel() const;
  inline void set_manurelevel(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:MsgSpreadManureReq)
 private:
  inline void set_has_manurelevel();
  inline void clear_has_manurelevel();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 manurelevel_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageFarmC2S_2eproto();
  friend void protobuf_AssignDesc_MessageFarmC2S_2eproto();
  friend void protobuf_ShutdownFile_MessageFarmC2S_2eproto();
  
  void InitAsDefaultInstance();
  static MsgSpreadManureReq* default_instance_;
};
// -------------------------------------------------------------------

class MsgGatherPloughCellReq : public ::google::protobuf::Message {
 public:
  MsgGatherPloughCellReq();
  virtual ~MsgGatherPloughCellReq();
  
  MsgGatherPloughCellReq(const MsgGatherPloughCellReq& from);
  
  inline MsgGatherPloughCellReq& operator=(const MsgGatherPloughCellReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgGatherPloughCellReq& default_instance();
  
  void Swap(MsgGatherPloughCellReq* other);
  
  // implements Message ----------------------------------------------
  
  MsgGatherPloughCellReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgGatherPloughCellReq& from);
  void MergeFrom(const MsgGatherPloughCellReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 cellid = 1;
  inline bool has_cellid() const;
  inline void clear_cellid();
  static const int kCellidFieldNumber = 1;
  inline ::google::protobuf::int32 cellid() const;
  inline void set_cellid(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:MsgGatherPloughCellReq)
 private:
  inline void set_has_cellid();
  inline void clear_has_cellid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 cellid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageFarmC2S_2eproto();
  friend void protobuf_AssignDesc_MessageFarmC2S_2eproto();
  friend void protobuf_ShutdownFile_MessageFarmC2S_2eproto();
  
  void InitAsDefaultInstance();
  static MsgGatherPloughCellReq* default_instance_;
};
// -------------------------------------------------------------------

class MsgWaterCellReq : public ::google::protobuf::Message {
 public:
  MsgWaterCellReq();
  virtual ~MsgWaterCellReq();
  
  MsgWaterCellReq(const MsgWaterCellReq& from);
  
  inline MsgWaterCellReq& operator=(const MsgWaterCellReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgWaterCellReq& default_instance();
  
  void Swap(MsgWaterCellReq* other);
  
  // implements Message ----------------------------------------------
  
  MsgWaterCellReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgWaterCellReq& from);
  void MergeFrom(const MsgWaterCellReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 cellid = 1;
  inline bool has_cellid() const;
  inline void clear_cellid();
  static const int kCellidFieldNumber = 1;
  inline ::google::protobuf::int32 cellid() const;
  inline void set_cellid(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:MsgWaterCellReq)
 private:
  inline void set_has_cellid();
  inline void clear_has_cellid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 cellid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageFarmC2S_2eproto();
  friend void protobuf_AssignDesc_MessageFarmC2S_2eproto();
  friend void protobuf_ShutdownFile_MessageFarmC2S_2eproto();
  
  void InitAsDefaultInstance();
  static MsgWaterCellReq* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgFarmStateReq

// -------------------------------------------------------------------

// MsgSeedCellReq

// required int32 seedlevel = 1;
inline bool MsgSeedCellReq::has_seedlevel() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgSeedCellReq::set_has_seedlevel() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgSeedCellReq::clear_has_seedlevel() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgSeedCellReq::clear_seedlevel() {
  seedlevel_ = 0;
  clear_has_seedlevel();
}
inline ::google::protobuf::int32 MsgSeedCellReq::seedlevel() const {
  return seedlevel_;
}
inline void MsgSeedCellReq::set_seedlevel(::google::protobuf::int32 value) {
  set_has_seedlevel();
  seedlevel_ = value;
}

// -------------------------------------------------------------------

// MsgSpreadManureReq

// required int32 manurelevel = 1;
inline bool MsgSpreadManureReq::has_manurelevel() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgSpreadManureReq::set_has_manurelevel() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgSpreadManureReq::clear_has_manurelevel() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgSpreadManureReq::clear_manurelevel() {
  manurelevel_ = 0;
  clear_has_manurelevel();
}
inline ::google::protobuf::int32 MsgSpreadManureReq::manurelevel() const {
  return manurelevel_;
}
inline void MsgSpreadManureReq::set_manurelevel(::google::protobuf::int32 value) {
  set_has_manurelevel();
  manurelevel_ = value;
}

// -------------------------------------------------------------------

// MsgGatherPloughCellReq

// required int32 cellid = 1;
inline bool MsgGatherPloughCellReq::has_cellid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgGatherPloughCellReq::set_has_cellid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgGatherPloughCellReq::clear_has_cellid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgGatherPloughCellReq::clear_cellid() {
  cellid_ = 0;
  clear_has_cellid();
}
inline ::google::protobuf::int32 MsgGatherPloughCellReq::cellid() const {
  return cellid_;
}
inline void MsgGatherPloughCellReq::set_cellid(::google::protobuf::int32 value) {
  set_has_cellid();
  cellid_ = value;
}

// -------------------------------------------------------------------

// MsgWaterCellReq

// required int32 cellid = 1;
inline bool MsgWaterCellReq::has_cellid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgWaterCellReq::set_has_cellid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgWaterCellReq::clear_has_cellid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgWaterCellReq::clear_cellid() {
  cellid_ = 0;
  clear_has_cellid();
}
inline ::google::protobuf::int32 MsgWaterCellReq::cellid() const {
  return cellid_;
}
inline void MsgWaterCellReq::set_cellid(::google::protobuf::int32 value) {
  set_has_cellid();
  cellid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageFarmC2S_2eproto__INCLUDED
