// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageGate2LG.proto

#ifndef PROTOBUF_MessageGate2LG_2eproto__INCLUDED
#define PROTOBUF_MessageGate2LG_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "MsgHead.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageGate2LG_2eproto();
void protobuf_AssignDesc_MessageGate2LG_2eproto();
void protobuf_ShutdownFile_MessageGate2LG_2eproto();

class MsgGate2LGLoginReq;
class MsgGate2LGClientDisconnect;

// ===================================================================

class MsgGate2LGLoginReq : public ::google::protobuf::Message {
 public:
  MsgGate2LGLoginReq();
  virtual ~MsgGate2LGLoginReq();
  
  MsgGate2LGLoginReq(const MsgGate2LGLoginReq& from);
  
  inline MsgGate2LGLoginReq& operator=(const MsgGate2LGLoginReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgGate2LGLoginReq& default_instance();
  
  void Swap(MsgGate2LGLoginReq* other);
  
  // implements Message ----------------------------------------------
  
  MsgGate2LGLoginReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgGate2LGLoginReq& from);
  void MergeFrom(const MsgGate2LGLoginReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);
  
  // required string mac = 2;
  inline bool has_mac() const;
  inline void clear_mac();
  static const int kMacFieldNumber = 2;
  inline const ::std::string& mac() const;
  inline void set_mac(const ::std::string& value);
  inline void set_mac(const char* value);
  inline void set_mac(const char* value, size_t size);
  inline ::std::string* mutable_mac();
  inline ::std::string* release_mac();
  
  // @@protoc_insertion_point(class_scope:MsgGate2LGLoginReq)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_mac();
  inline void clear_has_mac();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 id_;
  ::std::string* mac_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageGate2LG_2eproto();
  friend void protobuf_AssignDesc_MessageGate2LG_2eproto();
  friend void protobuf_ShutdownFile_MessageGate2LG_2eproto();
  
  void InitAsDefaultInstance();
  static MsgGate2LGLoginReq* default_instance_;
};
// -------------------------------------------------------------------

class MsgGate2LGClientDisconnect : public ::google::protobuf::Message {
 public:
  MsgGate2LGClientDisconnect();
  virtual ~MsgGate2LGClientDisconnect();
  
  MsgGate2LGClientDisconnect(const MsgGate2LGClientDisconnect& from);
  
  inline MsgGate2LGClientDisconnect& operator=(const MsgGate2LGClientDisconnect& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgGate2LGClientDisconnect& default_instance();
  
  void Swap(MsgGate2LGClientDisconnect* other);
  
  // implements Message ----------------------------------------------
  
  MsgGate2LGClientDisconnect* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgGate2LGClientDisconnect& from);
  void MergeFrom(const MsgGate2LGClientDisconnect& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:MsgGate2LGClientDisconnect)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageGate2LG_2eproto();
  friend void protobuf_AssignDesc_MessageGate2LG_2eproto();
  friend void protobuf_ShutdownFile_MessageGate2LG_2eproto();
  
  void InitAsDefaultInstance();
  static MsgGate2LGClientDisconnect* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgGate2LGLoginReq

// required uint64 id = 1;
inline bool MsgGate2LGLoginReq::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgGate2LGLoginReq::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgGate2LGLoginReq::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgGate2LGLoginReq::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 MsgGate2LGLoginReq::id() const {
  return id_;
}
inline void MsgGate2LGLoginReq::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
}

// required string mac = 2;
inline bool MsgGate2LGLoginReq::has_mac() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgGate2LGLoginReq::set_has_mac() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgGate2LGLoginReq::clear_has_mac() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgGate2LGLoginReq::clear_mac() {
  if (mac_ != &::google::protobuf::internal::kEmptyString) {
    mac_->clear();
  }
  clear_has_mac();
}
inline const ::std::string& MsgGate2LGLoginReq::mac() const {
  return *mac_;
}
inline void MsgGate2LGLoginReq::set_mac(const ::std::string& value) {
  set_has_mac();
  if (mac_ == &::google::protobuf::internal::kEmptyString) {
    mac_ = new ::std::string;
  }
  mac_->assign(value);
}
inline void MsgGate2LGLoginReq::set_mac(const char* value) {
  set_has_mac();
  if (mac_ == &::google::protobuf::internal::kEmptyString) {
    mac_ = new ::std::string;
  }
  mac_->assign(value);
}
inline void MsgGate2LGLoginReq::set_mac(const char* value, size_t size) {
  set_has_mac();
  if (mac_ == &::google::protobuf::internal::kEmptyString) {
    mac_ = new ::std::string;
  }
  mac_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MsgGate2LGLoginReq::mutable_mac() {
  set_has_mac();
  if (mac_ == &::google::protobuf::internal::kEmptyString) {
    mac_ = new ::std::string;
  }
  return mac_;
}
inline ::std::string* MsgGate2LGLoginReq::release_mac() {
  clear_has_mac();
  if (mac_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mac_;
    mac_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// MsgGate2LGClientDisconnect

// required uint64 id = 1;
inline bool MsgGate2LGClientDisconnect::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgGate2LGClientDisconnect::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgGate2LGClientDisconnect::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgGate2LGClientDisconnect::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 MsgGate2LGClientDisconnect::id() const {
  return id_;
}
inline void MsgGate2LGClientDisconnect::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageGate2LG_2eproto__INCLUDED
