// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageGate2GS.proto

#ifndef PROTOBUF_MessageGate2GS_2eproto__INCLUDED
#define PROTOBUF_MessageGate2GS_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "MsgHead.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageGate2GS_2eproto();
void protobuf_AssignDesc_MessageGate2GS_2eproto();
void protobuf_ShutdownFile_MessageGate2GS_2eproto();

class MsgGate2GSLoginReq;

// ===================================================================

class MsgGate2GSLoginReq : public ::google::protobuf::Message {
 public:
  MsgGate2GSLoginReq();
  virtual ~MsgGate2GSLoginReq();
  
  MsgGate2GSLoginReq(const MsgGate2GSLoginReq& from);
  
  inline MsgGate2GSLoginReq& operator=(const MsgGate2GSLoginReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgGate2GSLoginReq& default_instance();
  
  void Swap(MsgGate2GSLoginReq* other);
  
  // implements Message ----------------------------------------------
  
  MsgGate2GSLoginReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgGate2GSLoginReq& from);
  void MergeFrom(const MsgGate2GSLoginReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint64 account = 1;
  inline bool has_account() const;
  inline void clear_account();
  static const int kAccountFieldNumber = 1;
  inline ::google::protobuf::uint64 account() const;
  inline void set_account(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:MsgGate2GSLoginReq)
 private:
  inline void set_has_account();
  inline void clear_has_account();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 account_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageGate2GS_2eproto();
  friend void protobuf_AssignDesc_MessageGate2GS_2eproto();
  friend void protobuf_ShutdownFile_MessageGate2GS_2eproto();
  
  void InitAsDefaultInstance();
  static MsgGate2GSLoginReq* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgGate2GSLoginReq

// required uint64 account = 1;
inline bool MsgGate2GSLoginReq::has_account() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgGate2GSLoginReq::set_has_account() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgGate2GSLoginReq::clear_has_account() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgGate2GSLoginReq::clear_account() {
  account_ = GOOGLE_ULONGLONG(0);
  clear_has_account();
}
inline ::google::protobuf::uint64 MsgGate2GSLoginReq::account() const {
  return account_;
}
inline void MsgGate2GSLoginReq::set_account(::google::protobuf::uint64 value) {
  set_has_account();
  account_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageGate2GS_2eproto__INCLUDED
