// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageG2C.proto

#ifndef PROTOBUF_MessageG2C_2eproto__INCLUDED
#define PROTOBUF_MessageG2C_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "MsgHead.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageG2C_2eproto();
void protobuf_AssignDesc_MessageG2C_2eproto();
void protobuf_ShutdownFile_MessageG2C_2eproto();

class MsgG2CLoginACK;
class MsgG2CErrorACK;
class MsgFarmErrorACK;
class MsgSeedCellACK;
class MsgSpreadManureACK;
class MsgGatherPloughCellACK;

enum MsgG2CErrorACK_enResult {
  MsgG2CErrorACK_enResult_LG_UNKNOW = 0,
  MsgG2CErrorACK_enResult_LG_ALREADYLOGIN = 1,
  MsgG2CErrorACK_enResult_LG_YOUARENOTLOGIN = 2,
  MsgG2CErrorACK_enResult_LG_NOTFOUNDPLAYER = 3
};
bool MsgG2CErrorACK_enResult_IsValid(int value);
const MsgG2CErrorACK_enResult MsgG2CErrorACK_enResult_enResult_MIN = MsgG2CErrorACK_enResult_LG_UNKNOW;
const MsgG2CErrorACK_enResult MsgG2CErrorACK_enResult_enResult_MAX = MsgG2CErrorACK_enResult_LG_NOTFOUNDPLAYER;
const int MsgG2CErrorACK_enResult_enResult_ARRAYSIZE = MsgG2CErrorACK_enResult_enResult_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgG2CErrorACK_enResult_descriptor();
inline const ::std::string& MsgG2CErrorACK_enResult_Name(MsgG2CErrorACK_enResult value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgG2CErrorACK_enResult_descriptor(), value);
}
inline bool MsgG2CErrorACK_enResult_Parse(
    const ::std::string& name, MsgG2CErrorACK_enResult* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgG2CErrorACK_enResult>(
    MsgG2CErrorACK_enResult_descriptor(), name, value);
}
enum enFarmErrorResult {
  FarmError_NOTFOUNDCELL = 0,
  FarmError_NOTHAVESEED = 1,
  FarmError_CELLCANNOTSEED = 2,
  FarmError_ISHAVEMANURE = 3,
  FarmError_GATHERNOTGROWNCELL = 4,
  FarmError_UKNOWN = 5
};
bool enFarmErrorResult_IsValid(int value);
const enFarmErrorResult enFarmErrorResult_MIN = FarmError_NOTFOUNDCELL;
const enFarmErrorResult enFarmErrorResult_MAX = FarmError_UKNOWN;
const int enFarmErrorResult_ARRAYSIZE = enFarmErrorResult_MAX + 1;

const ::google::protobuf::EnumDescriptor* enFarmErrorResult_descriptor();
inline const ::std::string& enFarmErrorResult_Name(enFarmErrorResult value) {
  return ::google::protobuf::internal::NameOfEnum(
    enFarmErrorResult_descriptor(), value);
}
inline bool enFarmErrorResult_Parse(
    const ::std::string& name, enFarmErrorResult* value) {
  return ::google::protobuf::internal::ParseNamedEnum<enFarmErrorResult>(
    enFarmErrorResult_descriptor(), name, value);
}
// ===================================================================

class MsgG2CLoginACK : public ::google::protobuf::Message {
 public:
  MsgG2CLoginACK();
  virtual ~MsgG2CLoginACK();
  
  MsgG2CLoginACK(const MsgG2CLoginACK& from);
  
  inline MsgG2CLoginACK& operator=(const MsgG2CLoginACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgG2CLoginACK& default_instance();
  
  void Swap(MsgG2CLoginACK* other);
  
  // implements Message ----------------------------------------------
  
  MsgG2CLoginACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgG2CLoginACK& from);
  void MergeFrom(const MsgG2CLoginACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint64 account = 1;
  inline bool has_account() const;
  inline void clear_account();
  static const int kAccountFieldNumber = 1;
  inline ::google::protobuf::uint64 account() const;
  inline void set_account(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:MsgG2CLoginACK)
 private:
  inline void set_has_account();
  inline void clear_has_account();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 account_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageG2C_2eproto();
  friend void protobuf_AssignDesc_MessageG2C_2eproto();
  friend void protobuf_ShutdownFile_MessageG2C_2eproto();
  
  void InitAsDefaultInstance();
  static MsgG2CLoginACK* default_instance_;
};
// -------------------------------------------------------------------

class MsgG2CErrorACK : public ::google::protobuf::Message {
 public:
  MsgG2CErrorACK();
  virtual ~MsgG2CErrorACK();
  
  MsgG2CErrorACK(const MsgG2CErrorACK& from);
  
  inline MsgG2CErrorACK& operator=(const MsgG2CErrorACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgG2CErrorACK& default_instance();
  
  void Swap(MsgG2CErrorACK* other);
  
  // implements Message ----------------------------------------------
  
  MsgG2CErrorACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgG2CErrorACK& from);
  void MergeFrom(const MsgG2CErrorACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef MsgG2CErrorACK_enResult enResult;
  static const enResult LG_UNKNOW = MsgG2CErrorACK_enResult_LG_UNKNOW;
  static const enResult LG_ALREADYLOGIN = MsgG2CErrorACK_enResult_LG_ALREADYLOGIN;
  static const enResult LG_YOUARENOTLOGIN = MsgG2CErrorACK_enResult_LG_YOUARENOTLOGIN;
  static const enResult LG_NOTFOUNDPLAYER = MsgG2CErrorACK_enResult_LG_NOTFOUNDPLAYER;
  static inline bool enResult_IsValid(int value) {
    return MsgG2CErrorACK_enResult_IsValid(value);
  }
  static const enResult enResult_MIN =
    MsgG2CErrorACK_enResult_enResult_MIN;
  static const enResult enResult_MAX =
    MsgG2CErrorACK_enResult_enResult_MAX;
  static const int enResult_ARRAYSIZE =
    MsgG2CErrorACK_enResult_enResult_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  enResult_descriptor() {
    return MsgG2CErrorACK_enResult_descriptor();
  }
  static inline const ::std::string& enResult_Name(enResult value) {
    return MsgG2CErrorACK_enResult_Name(value);
  }
  static inline bool enResult_Parse(const ::std::string& name,
      enResult* value) {
    return MsgG2CErrorACK_enResult_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // required .MsgG2CErrorACK.enResult en = 1;
  inline bool has_en() const;
  inline void clear_en();
  static const int kEnFieldNumber = 1;
  inline ::MsgG2CErrorACK_enResult en() const;
  inline void set_en(::MsgG2CErrorACK_enResult value);
  
  // @@protoc_insertion_point(class_scope:MsgG2CErrorACK)
 private:
  inline void set_has_en();
  inline void clear_has_en();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  int en_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageG2C_2eproto();
  friend void protobuf_AssignDesc_MessageG2C_2eproto();
  friend void protobuf_ShutdownFile_MessageG2C_2eproto();
  
  void InitAsDefaultInstance();
  static MsgG2CErrorACK* default_instance_;
};
// -------------------------------------------------------------------

class MsgFarmErrorACK : public ::google::protobuf::Message {
 public:
  MsgFarmErrorACK();
  virtual ~MsgFarmErrorACK();
  
  MsgFarmErrorACK(const MsgFarmErrorACK& from);
  
  inline MsgFarmErrorACK& operator=(const MsgFarmErrorACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgFarmErrorACK& default_instance();
  
  void Swap(MsgFarmErrorACK* other);
  
  // implements Message ----------------------------------------------
  
  MsgFarmErrorACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgFarmErrorACK& from);
  void MergeFrom(const MsgFarmErrorACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .enFarmErrorResult en = 1;
  inline bool has_en() const;
  inline void clear_en();
  static const int kEnFieldNumber = 1;
  inline enFarmErrorResult en() const;
  inline void set_en(enFarmErrorResult value);
  
  // required int32 cellid = 2;
  inline bool has_cellid() const;
  inline void clear_cellid();
  static const int kCellidFieldNumber = 2;
  inline ::google::protobuf::int32 cellid() const;
  inline void set_cellid(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:MsgFarmErrorACK)
 private:
  inline void set_has_en();
  inline void clear_has_en();
  inline void set_has_cellid();
  inline void clear_has_cellid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  int en_;
  ::google::protobuf::int32 cellid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageG2C_2eproto();
  friend void protobuf_AssignDesc_MessageG2C_2eproto();
  friend void protobuf_ShutdownFile_MessageG2C_2eproto();
  
  void InitAsDefaultInstance();
  static MsgFarmErrorACK* default_instance_;
};
// -------------------------------------------------------------------

class MsgSeedCellACK : public ::google::protobuf::Message {
 public:
  MsgSeedCellACK();
  virtual ~MsgSeedCellACK();
  
  MsgSeedCellACK(const MsgSeedCellACK& from);
  
  inline MsgSeedCellACK& operator=(const MsgSeedCellACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgSeedCellACK& default_instance();
  
  void Swap(MsgSeedCellACK* other);
  
  // implements Message ----------------------------------------------
  
  MsgSeedCellACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgSeedCellACK& from);
  void MergeFrom(const MsgSeedCellACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 cellid = 2;
  inline bool has_cellid() const;
  inline void clear_cellid();
  static const int kCellidFieldNumber = 2;
  inline ::google::protobuf::int32 cellid() const;
  inline void set_cellid(::google::protobuf::int32 value);
  
  // required int32 seedlevel = 3;
  inline bool has_seedlevel() const;
  inline void clear_seedlevel();
  static const int kSeedlevelFieldNumber = 3;
  inline ::google::protobuf::int32 seedlevel() const;
  inline void set_seedlevel(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:MsgSeedCellACK)
 private:
  inline void set_has_cellid();
  inline void clear_has_cellid();
  inline void set_has_seedlevel();
  inline void clear_has_seedlevel();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 cellid_;
  ::google::protobuf::int32 seedlevel_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageG2C_2eproto();
  friend void protobuf_AssignDesc_MessageG2C_2eproto();
  friend void protobuf_ShutdownFile_MessageG2C_2eproto();
  
  void InitAsDefaultInstance();
  static MsgSeedCellACK* default_instance_;
};
// -------------------------------------------------------------------

class MsgSpreadManureACK : public ::google::protobuf::Message {
 public:
  MsgSpreadManureACK();
  virtual ~MsgSpreadManureACK();
  
  MsgSpreadManureACK(const MsgSpreadManureACK& from);
  
  inline MsgSpreadManureACK& operator=(const MsgSpreadManureACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgSpreadManureACK& default_instance();
  
  void Swap(MsgSpreadManureACK* other);
  
  // implements Message ----------------------------------------------
  
  MsgSpreadManureACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgSpreadManureACK& from);
  void MergeFrom(const MsgSpreadManureACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 cellid = 1;
  inline bool has_cellid() const;
  inline void clear_cellid();
  static const int kCellidFieldNumber = 1;
  inline ::google::protobuf::int32 cellid() const;
  inline void set_cellid(::google::protobuf::int32 value);
  
  // required int32 manurelevel = 2;
  inline bool has_manurelevel() const;
  inline void clear_manurelevel();
  static const int kManurelevelFieldNumber = 2;
  inline ::google::protobuf::int32 manurelevel() const;
  inline void set_manurelevel(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:MsgSpreadManureACK)
 private:
  inline void set_has_cellid();
  inline void clear_has_cellid();
  inline void set_has_manurelevel();
  inline void clear_has_manurelevel();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 cellid_;
  ::google::protobuf::int32 manurelevel_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageG2C_2eproto();
  friend void protobuf_AssignDesc_MessageG2C_2eproto();
  friend void protobuf_ShutdownFile_MessageG2C_2eproto();
  
  void InitAsDefaultInstance();
  static MsgSpreadManureACK* default_instance_;
};
// -------------------------------------------------------------------

class MsgGatherPloughCellACK : public ::google::protobuf::Message {
 public:
  MsgGatherPloughCellACK();
  virtual ~MsgGatherPloughCellACK();
  
  MsgGatherPloughCellACK(const MsgGatherPloughCellACK& from);
  
  inline MsgGatherPloughCellACK& operator=(const MsgGatherPloughCellACK& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgGatherPloughCellACK& default_instance();
  
  void Swap(MsgGatherPloughCellACK* other);
  
  // implements Message ----------------------------------------------
  
  MsgGatherPloughCellACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgGatherPloughCellACK& from);
  void MergeFrom(const MsgGatherPloughCellACK& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 cellid = 1;
  inline bool has_cellid() const;
  inline void clear_cellid();
  static const int kCellidFieldNumber = 1;
  inline ::google::protobuf::int32 cellid() const;
  inline void set_cellid(::google::protobuf::int32 value);
  
  // required int32 resource = 2;
  inline bool has_resource() const;
  inline void clear_resource();
  static const int kResourceFieldNumber = 2;
  inline ::google::protobuf::int32 resource() const;
  inline void set_resource(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:MsgGatherPloughCellACK)
 private:
  inline void set_has_cellid();
  inline void clear_has_cellid();
  inline void set_has_resource();
  inline void clear_has_resource();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 cellid_;
  ::google::protobuf::int32 resource_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_MessageG2C_2eproto();
  friend void protobuf_AssignDesc_MessageG2C_2eproto();
  friend void protobuf_ShutdownFile_MessageG2C_2eproto();
  
  void InitAsDefaultInstance();
  static MsgGatherPloughCellACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgG2CLoginACK

// required uint64 account = 1;
inline bool MsgG2CLoginACK::has_account() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgG2CLoginACK::set_has_account() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgG2CLoginACK::clear_has_account() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgG2CLoginACK::clear_account() {
  account_ = GOOGLE_ULONGLONG(0);
  clear_has_account();
}
inline ::google::protobuf::uint64 MsgG2CLoginACK::account() const {
  return account_;
}
inline void MsgG2CLoginACK::set_account(::google::protobuf::uint64 value) {
  set_has_account();
  account_ = value;
}

// -------------------------------------------------------------------

// MsgG2CErrorACK

// required .MsgG2CErrorACK.enResult en = 1;
inline bool MsgG2CErrorACK::has_en() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgG2CErrorACK::set_has_en() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgG2CErrorACK::clear_has_en() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgG2CErrorACK::clear_en() {
  en_ = 0;
  clear_has_en();
}
inline ::MsgG2CErrorACK_enResult MsgG2CErrorACK::en() const {
  return static_cast< ::MsgG2CErrorACK_enResult >(en_);
}
inline void MsgG2CErrorACK::set_en(::MsgG2CErrorACK_enResult value) {
  GOOGLE_DCHECK(::MsgG2CErrorACK_enResult_IsValid(value));
  set_has_en();
  en_ = value;
}

// -------------------------------------------------------------------

// MsgFarmErrorACK

// required .enFarmErrorResult en = 1;
inline bool MsgFarmErrorACK::has_en() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgFarmErrorACK::set_has_en() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgFarmErrorACK::clear_has_en() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgFarmErrorACK::clear_en() {
  en_ = 0;
  clear_has_en();
}
inline enFarmErrorResult MsgFarmErrorACK::en() const {
  return static_cast< enFarmErrorResult >(en_);
}
inline void MsgFarmErrorACK::set_en(enFarmErrorResult value) {
  GOOGLE_DCHECK(enFarmErrorResult_IsValid(value));
  set_has_en();
  en_ = value;
}

// required int32 cellid = 2;
inline bool MsgFarmErrorACK::has_cellid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgFarmErrorACK::set_has_cellid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgFarmErrorACK::clear_has_cellid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgFarmErrorACK::clear_cellid() {
  cellid_ = 0;
  clear_has_cellid();
}
inline ::google::protobuf::int32 MsgFarmErrorACK::cellid() const {
  return cellid_;
}
inline void MsgFarmErrorACK::set_cellid(::google::protobuf::int32 value) {
  set_has_cellid();
  cellid_ = value;
}

// -------------------------------------------------------------------

// MsgSeedCellACK

// required int32 cellid = 2;
inline bool MsgSeedCellACK::has_cellid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgSeedCellACK::set_has_cellid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgSeedCellACK::clear_has_cellid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgSeedCellACK::clear_cellid() {
  cellid_ = 0;
  clear_has_cellid();
}
inline ::google::protobuf::int32 MsgSeedCellACK::cellid() const {
  return cellid_;
}
inline void MsgSeedCellACK::set_cellid(::google::protobuf::int32 value) {
  set_has_cellid();
  cellid_ = value;
}

// required int32 seedlevel = 3;
inline bool MsgSeedCellACK::has_seedlevel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgSeedCellACK::set_has_seedlevel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgSeedCellACK::clear_has_seedlevel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgSeedCellACK::clear_seedlevel() {
  seedlevel_ = 0;
  clear_has_seedlevel();
}
inline ::google::protobuf::int32 MsgSeedCellACK::seedlevel() const {
  return seedlevel_;
}
inline void MsgSeedCellACK::set_seedlevel(::google::protobuf::int32 value) {
  set_has_seedlevel();
  seedlevel_ = value;
}

// -------------------------------------------------------------------

// MsgSpreadManureACK

// required int32 cellid = 1;
inline bool MsgSpreadManureACK::has_cellid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgSpreadManureACK::set_has_cellid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgSpreadManureACK::clear_has_cellid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgSpreadManureACK::clear_cellid() {
  cellid_ = 0;
  clear_has_cellid();
}
inline ::google::protobuf::int32 MsgSpreadManureACK::cellid() const {
  return cellid_;
}
inline void MsgSpreadManureACK::set_cellid(::google::protobuf::int32 value) {
  set_has_cellid();
  cellid_ = value;
}

// required int32 manurelevel = 2;
inline bool MsgSpreadManureACK::has_manurelevel() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgSpreadManureACK::set_has_manurelevel() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgSpreadManureACK::clear_has_manurelevel() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgSpreadManureACK::clear_manurelevel() {
  manurelevel_ = 0;
  clear_has_manurelevel();
}
inline ::google::protobuf::int32 MsgSpreadManureACK::manurelevel() const {
  return manurelevel_;
}
inline void MsgSpreadManureACK::set_manurelevel(::google::protobuf::int32 value) {
  set_has_manurelevel();
  manurelevel_ = value;
}

// -------------------------------------------------------------------

// MsgGatherPloughCellACK

// required int32 cellid = 1;
inline bool MsgGatherPloughCellACK::has_cellid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgGatherPloughCellACK::set_has_cellid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgGatherPloughCellACK::clear_has_cellid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgGatherPloughCellACK::clear_cellid() {
  cellid_ = 0;
  clear_has_cellid();
}
inline ::google::protobuf::int32 MsgGatherPloughCellACK::cellid() const {
  return cellid_;
}
inline void MsgGatherPloughCellACK::set_cellid(::google::protobuf::int32 value) {
  set_has_cellid();
  cellid_ = value;
}

// required int32 resource = 2;
inline bool MsgGatherPloughCellACK::has_resource() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgGatherPloughCellACK::set_has_resource() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgGatherPloughCellACK::clear_has_resource() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgGatherPloughCellACK::clear_resource() {
  resource_ = 0;
  clear_has_resource();
}
inline ::google::protobuf::int32 MsgGatherPloughCellACK::resource() const {
  return resource_;
}
inline void MsgGatherPloughCellACK::set_resource(::google::protobuf::int32 value) {
  set_has_resource();
  resource_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MsgG2CErrorACK_enResult>() {
  return ::MsgG2CErrorACK_enResult_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< enFarmErrorResult>() {
  return enFarmErrorResult_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageG2C_2eproto__INCLUDED
