// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageLG2Gate.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MsgLG2GateLoginACK_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MsgLG2GateLoginACK_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* MsgLG2GateLoginACK_enResult_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageLG2Gate_2eproto() {
  protobuf_AddDesc_MessageLG2Gate_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageLG2Gate.proto");
  GOOGLE_CHECK(file != NULL);
  MsgLG2GateLoginACK_descriptor_ = file->message_type(0);
  static const int MsgLG2GateLoginACK_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgLG2GateLoginACK, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgLG2GateLoginACK, result_),
  };
  MsgLG2GateLoginACK_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MsgLG2GateLoginACK_descriptor_,
      MsgLG2GateLoginACK::default_instance_,
      MsgLG2GateLoginACK_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgLG2GateLoginACK, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MsgLG2GateLoginACK, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MsgLG2GateLoginACK));
  MsgLG2GateLoginACK_enResult_descriptor_ = MsgLG2GateLoginACK_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageLG2Gate_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MsgLG2GateLoginACK_descriptor_, &MsgLG2GateLoginACK::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageLG2Gate_2eproto() {
  delete MsgLG2GateLoginACK::default_instance_;
  delete MsgLG2GateLoginACK_reflection_;
}

void protobuf_AddDesc_MessageLG2Gate_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_MsgHead_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024MessageLG2Gate.proto\032\rMsgHead.proto\"s\n"
    "\022MsgLG2GateLoginACK\022\n\n\002id\030\001 \002(\003\022,\n\006resul"
    "t\030\002 \002(\0162\034.MsgLG2GateLoginACK.enResult\"#\n"
    "\010enResult\022\t\n\005LG_OK\020\000\022\014\n\010LG_ERROR\020\001", 154);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageLG2Gate.proto", &protobuf_RegisterTypes);
  MsgLG2GateLoginACK::default_instance_ = new MsgLG2GateLoginACK();
  MsgLG2GateLoginACK::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageLG2Gate_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageLG2Gate_2eproto {
  StaticDescriptorInitializer_MessageLG2Gate_2eproto() {
    protobuf_AddDesc_MessageLG2Gate_2eproto();
  }
} static_descriptor_initializer_MessageLG2Gate_2eproto_;


// ===================================================================

const ::google::protobuf::EnumDescriptor* MsgLG2GateLoginACK_enResult_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgLG2GateLoginACK_enResult_descriptor_;
}
bool MsgLG2GateLoginACK_enResult_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const MsgLG2GateLoginACK_enResult MsgLG2GateLoginACK::LG_OK;
const MsgLG2GateLoginACK_enResult MsgLG2GateLoginACK::LG_ERROR;
const MsgLG2GateLoginACK_enResult MsgLG2GateLoginACK::enResult_MIN;
const MsgLG2GateLoginACK_enResult MsgLG2GateLoginACK::enResult_MAX;
const int MsgLG2GateLoginACK::enResult_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int MsgLG2GateLoginACK::kIdFieldNumber;
const int MsgLG2GateLoginACK::kResultFieldNumber;
#endif  // !_MSC_VER

MsgLG2GateLoginACK::MsgLG2GateLoginACK()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MsgLG2GateLoginACK::InitAsDefaultInstance() {
}

MsgLG2GateLoginACK::MsgLG2GateLoginACK(const MsgLG2GateLoginACK& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MsgLG2GateLoginACK::SharedCtor() {
  _cached_size_ = 0;
  id_ = GOOGLE_LONGLONG(0);
  result_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MsgLG2GateLoginACK::~MsgLG2GateLoginACK() {
  SharedDtor();
}

void MsgLG2GateLoginACK::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MsgLG2GateLoginACK::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MsgLG2GateLoginACK::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgLG2GateLoginACK_descriptor_;
}

const MsgLG2GateLoginACK& MsgLG2GateLoginACK::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageLG2Gate_2eproto();  return *default_instance_;
}

MsgLG2GateLoginACK* MsgLG2GateLoginACK::default_instance_ = NULL;

MsgLG2GateLoginACK* MsgLG2GateLoginACK::New() const {
  return new MsgLG2GateLoginACK;
}

void MsgLG2GateLoginACK::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = GOOGLE_LONGLONG(0);
    result_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MsgLG2GateLoginACK::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_result;
        break;
      }
      
      // required .MsgLG2GateLoginACK.enResult result = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_result:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::MsgLG2GateLoginACK_enResult_IsValid(value)) {
            set_result(static_cast< ::MsgLG2GateLoginACK_enResult >(value));
          } else {
            mutable_unknown_fields()->AddVarint(2, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MsgLG2GateLoginACK::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->id(), output);
  }
  
  // required .MsgLG2GateLoginACK.enResult result = 2;
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->result(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MsgLG2GateLoginACK::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->id(), target);
  }
  
  // required .MsgLG2GateLoginACK.enResult result = 2;
  if (has_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->result(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MsgLG2GateLoginACK::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->id());
    }
    
    // required .MsgLG2GateLoginACK.enResult result = 2;
    if (has_result()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->result());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MsgLG2GateLoginACK::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MsgLG2GateLoginACK* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MsgLG2GateLoginACK*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MsgLG2GateLoginACK::MergeFrom(const MsgLG2GateLoginACK& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_result()) {
      set_result(from.result());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MsgLG2GateLoginACK::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgLG2GateLoginACK::CopyFrom(const MsgLG2GateLoginACK& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgLG2GateLoginACK::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void MsgLG2GateLoginACK::Swap(MsgLG2GateLoginACK* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(result_, other->result_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MsgLG2GateLoginACK::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MsgLG2GateLoginACK_descriptor_;
  metadata.reflection = MsgLG2GateLoginACK_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
